CREATE TYPE "course_category_type" AS ENUM (
  'UC',
  'FC',
  'PC',
  'PE',
  'OE'
);

CREATE TYPE "role_type" AS ENUM (
  'Admin',
  'Faculty',
  'CAIA'
);

CREATE TYPE "purpose_type" AS ENUM (
  'Teaching Now',
  'Future Teaching',
  'Self Upskill'
);

CREATE TYPE "designation_type" AS ENUM (
  'Assistant Professor',
  'Associate Professor',
  'Professor'
);

CREATE TYPE "skill_type" AS ENUM (
  'Preskill',
  'Tech/Core',
  'Tool',
  'Applied',
  'Project'
);

CREATE TYPE "familiarity_type" AS ENUM (
  'Yes',
  'No',
  'NA'
);

CREATE TABLE "follows" (
  "following_user_id" integer,
  "followed_user_id" integer,
  "created_at" timestamp
);

CREATE TABLE "users" (
  "id" integer PRIMARY KEY,
  "username" varchar,
  "role" varchar,
  "created_at" timestamp
);

CREATE TABLE "posts" (
  "id" integer PRIMARY KEY,
  "title" varchar,
  "body" text,
  "user_id" integer NOT NULL,
  "status" varchar,
  "created_at" timestamp
);

CREATE TABLE "campus" (
  "campus_id" text PRIMARY KEY,
  "campus_name" text
);

CREATE TABLE "school" (
  "school_id" text PRIMARY KEY,
  "school_short_name" text,
  "school_full_name" text,
  "parent_campus_id" text
);

CREATE TABLE "department" (
  "department_id" text PRIMARY KEY,
  "department_short_name" text,
  "department_full_name" text,
  "parent_school_id" text
);

CREATE TABLE "employee" (
  "employee_id" text PRIMARY KEY,
  "employee_mail" text UNIQUE,
  "employee_name" text,
  "designation" designation_type,
  "joining_date" text,
  "department_id" text,
  "password" text,
  "role" role_type
);

CREATE TABLE "course" (
  "course_id" text PRIMARY KEY,
  "course_name" text,
  "course_category" course_category_type,
  "offered_department_id" text,
  "course_coordinator_id" text,
  "course_champion_id" text,
  "caia_coordinator_id" text
);

CREATE TABLE "course_faculty_mapping" (
  "mapping_id" text PRIMARY KEY,
  "course_id" text,
  "employee_id" text,
  "purpose" purpose_type
);

CREATE TABLE "skill" (
  "skill_id" text PRIMARY KEY,
  "skill_name" text,
  "skill_description" text
);

CREATE TABLE "subskill" (
  "subskill_id" text PRIMARY KEY,
  "subskill_name" text,
  "subskill_description" text,
  "skill_id" text,
  "required" "BOOLEAN"
);

CREATE TABLE "course_skill_mapping" (
  "mapping_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "skill_id" text,
  "course_id" text,
  "type" skill_type
);

CREATE TABLE "familiarity_mapping" (
  "marking_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "subskill_id" text,
  "employee_id" text,
  "familiarity" "BOOLEAN",
  "date_time" timestamp,
  "erased" "BOOLEAN"
);

COMMENT ON COLUMN "posts"."body" IS 'Content of the post';

ALTER TABLE "posts" ADD CONSTRAINT "user_posts" FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "follows" ADD FOREIGN KEY ("following_user_id") REFERENCES "users" ("id");

ALTER TABLE "follows" ADD FOREIGN KEY ("followed_user_id") REFERENCES "users" ("id");

ALTER TABLE "school" ADD CONSTRAINT "school_parent_campus_id_fkey" FOREIGN KEY ("parent_campus_id") REFERENCES "campus" ("campus_id");

ALTER TABLE "department" ADD CONSTRAINT "department_parent_school_id_fkey" FOREIGN KEY ("parent_school_id") REFERENCES "school" ("school_id");

ALTER TABLE "employee" ADD CONSTRAINT "employee_department_mapping_id_fkey" FOREIGN KEY ("department_id") REFERENCES "department" ("department_id");

ALTER TABLE "course" ADD CONSTRAINT "course_parent_department_id_fkey" FOREIGN KEY ("offered_department_id") REFERENCES "department" ("department_id");

ALTER TABLE "course" ADD CONSTRAINT "course_coordinator_fkey" FOREIGN KEY ("course_coordinator_id") REFERENCES "employee" ("employee_id");

ALTER TABLE "course" ADD CONSTRAINT "course_champion_fkey" FOREIGN KEY ("course_champion_id") REFERENCES "employee" ("employee_id");

ALTER TABLE "course" ADD CONSTRAINT "course_caia_coordinator_fkey" FOREIGN KEY ("caia_coordinator_id") REFERENCES "employee" ("employee_id");

ALTER TABLE "course_faculty_mapping" ADD CONSTRAINT "course_faculty_mapping_course_id_fkey" FOREIGN KEY ("course_id") REFERENCES "course" ("course_id");

ALTER TABLE "course_faculty_mapping" ADD CONSTRAINT "course_faculty_mapping_employee_id_fkey" FOREIGN KEY ("employee_id") REFERENCES "employee" ("employee_id");

ALTER TABLE "subskill" ADD CONSTRAINT "subskill_skill_id_fkey" FOREIGN KEY ("skill_id") REFERENCES "skill" ("skill_id");

ALTER TABLE "course_skill_mapping" ADD CONSTRAINT "course_skill_mapping_skill_id_fkey" FOREIGN KEY ("skill_id") REFERENCES "skill" ("skill_id");

ALTER TABLE "course_skill_mapping" ADD CONSTRAINT "course_skill_mapping_course_id_fkey" FOREIGN KEY ("course_id") REFERENCES "course" ("course_id");

ALTER TABLE "familiarity_mapping" ADD CONSTRAINT "rating_subskill_id_fkey" FOREIGN KEY ("subskill_id") REFERENCES "subskill" ("subskill_id");

ALTER TABLE "familiarity_mapping" ADD CONSTRAINT "rating_mapping_employee_id_fkey" FOREIGN KEY ("employee_id") REFERENCES "employee" ("employee_id");
